### ISSUE TITLE
(Small) Visual Issue present 

### ISSUE THREAD

**Issue by fshmcallister** [WoTTsecurity/wott-io#129]
- Random characters visible on top left hand corner of every page
- Probably an unclosed bracket somewhere 
- image included
<img width="1127" alt="Screenshot 2019-07-23 at 20 11 59" src="https://user-images.githubusercontent.com/22798416/61740367-5ed8cc00-ad86-11e9-8357-cb536008fea8.png">

**Comment by fshmcallister** [comment]
circled in top left corner

**Comment by etf-yrm** [comment]
@vpetersson @fshmcallister , This issue was resolved as part of another task.
