### ISSUE TITLE
Fix social media links in footer

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/wott-io#15]
There are links in the footer to social media channels.

* Remove everything other than Github and Twitter
* Link Twitter to https://twitter.com/wottsecurity
* Linkup Github to https://github.com/WoTTsecurity

**Comment by vpetersson** [comment]
<img width="210" alt="Screen Shot 2019-07-01 at 8 50 54 AM" src="https://user-images.githubusercontent.com/357664/60419607-987e4300-9bdd-11e9-9b4c-1a8ce7cc6e54.png">

**Comment by etf-yrm** [comment]
This complete in PR - https://github.com/WoTTsecurity/wott-io/pull/25

**Comment by etf-yrm** [comment]
closes #15
