### ISSUE TITLE
Mixpanel event tracking for website

### ISSUE THREAD

**Issue by AlEsmail** [WoTTsecurity/wott-io#179]
We need to be able to track user behavior through Mixpanel.

Let's start with tracking the following events:

-Every Get started button on each page (there are two or three on each)
-Log in
-Sign up

For each event, we need to also track what page they were on while triggering the event, along which one it was (if there are for instance multiple instances on a given page).

**Comment by vpetersson** [comment]
Note that this needs to converge into Mixpanel in the webapp. I.e. if someone does action Y before logging in, that needs to be tracked against the same user in dashboard. See aliases in [Best practices](https://help.mixpanel.com/hc/en-us/articles/115004497803-Identity-Management-Best-Practices).

Also, we should add [pageview trackin](https://help.mixpanel.com/hc/en-us/articles/115004568086-The-mp-page-view-Event)
