### ISSUE TITLE
Wott Dashboard: No Credentials Link

### ISSUE THREAD

**Issue by ChuckIT** [WoTTsecurity/wott-io#188]
Using a free account and having registered a node as seen in 
"Snapshot-2019-10-20 WoTT - Dashboard" 
![Screenshot_2019-10-20 WoTT - Dashboard](https://user-images.githubusercontent.com/2983847/67176843-9bfe2b80-f380-11e9-8fe2-cf63812e50f9.png)

I am attempting to follow  the directions in as shown in "Screenshot_2019-10-20 Web of Trusted Things - Using WoTT credentials to manage access to Screenly OSE". 
![Screenshot_2019-10-20 Web of Trusted Things - Using WoTT credentials to manage access to Screenly OSE](https://user-images.githubusercontent.com/2983847/67176856-afa99200-f380-11e9-9a6b-680fdcae1ac8.png)

As can be seen the links on the left of both screenshots do not correspond and as this is not covered in any related documentation I could discover I am at a loss as how to proceed. I would therefore recommend that the documentation be provided and/or updated.
Thanks
Thanks

**Comment by vpetersson** [comment]
@ChuckIT We hid that part from the user interface for now to streamline the user experience. A UI overhaul is on the roadmap. For the time being, you can access the credentials from [dash.wott.io/credentials/](https://dash.wott.io/credentials/).

**Comment by ChuckIT** [comment]
Thanks.On Oct 21, 2019 5:25 AM, Viktor Petersson <notifications@github.com> wrote:@ChuckIT We hid that part from the user interface for now to streamline the user experience. A UI overhaul is on the roadmap. For the time being, you can access the credentials from dash.wott.io/credentials/.
