### ISSUE TITLE
New pricing list

### ISSUE THREAD

**Issue by AlEsmail** [WoTTsecurity/wott-io#196]
Pricing is now according to the following:

- Pilot: 1st node is free
- Standard: $9/node
- Professional: Need bulk pricing - contact us

All plans are fully featured, so remove the lengthy lists of features from each plan.

Change text at top to 'First node is free and fully featured.'

![image](https://user-images.githubusercontent.com/36540135/69652573-c91db800-1069-11ea-8ea3-f40049a13ada.png)

Remove this dropdown menu - getting super annoying to change this every time
![image](https://user-images.githubusercontent.com/36540135/69654269-67128200-106c-11ea-9530-d602dcf5f1c4.png)

**Comment by vpetersson** [comment]
@AlEsmail I just looked at this briefly and it's a bit more complicated than this because of the drop-down and the plan selection integration with the back-end. I'll see if i can hack together a temporary solution.

**Comment by vpetersson** [comment]
@AlEsmail It's not pretty, but here it is:
<img width="1328" alt="Screen Shot 2019-11-27 at 9 31 14 AM" src="https://user-images.githubusercontent.com/357664/69711272-ac7c9100-10f8-11ea-9e73-b57678dc02a9.png">

Let me know what you think and I can roll it out.

**Comment by vpetersson** [comment]
Fixed in d8194ccdfd83ac79543f81baddc4e7a4bfea8100.
