### ISSUE TITLE
Products page issues

### ISSUE THREAD

**Issue by fshmcallister** [WoTTsecurity/wott-io#61]
- Are the images supposed to be clickable?
- ‘Learn more’ buttons don’t do anything

**Comment by etf-yrm** [comment]
It is necessary to formulate what needs to be done. Previously, "learn more" has already been removed.

**Comment by vpetersson** [comment]
I think we can close this out unless you disagree @fshmcallister.

**Comment by fshmcallister** [comment]
fine by me, thanks all
