### ISSUE TITLE
Blog post issues

### ISSUE THREAD

**Issue by fshmcallister** [WoTTsecurity/wott-io#64]
- ~~Blog posts invite readers to comment but there is no way to actually do this so far other than a header that shows 'comments'~~
- 'Telegram me' button on sharing doesn't work

**Comment by vpetersson** [comment]
@fshmcallister I think we've removed the comment block already.

**Comment by fshmcallister** [comment]
are we doing away with comments entirely?

**Comment by vpetersson** [comment]
Yeah, at least for now. It's a PITA to manage.
