### ISSUE TITLE
Finalize blog posts

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/wott-io#7]
@AlEsmail wrote a [few blog posts](https://docs.google.com/document/d/1yKv80QTdex8SC0RMH7pi-eiyVB3Gfn0qMvZMeHkU49c/edit?ts=5d0a646b#). I've done a rough porting of the blog posts, but they need some more attention and to be audited properly locally.

**Comment by etf-yrm** [comment]
no access to the document. When attempting to request access - a notification that this is not possible
