### ISSUE TITLE
Fix titles of posts

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/wott-io#97]
The title tag should look something like this:

`{{ site.title-prefix}} - {{ page.title }}`

Right now, it's just `page.title`

**Comment by etf-yrm** [comment]
@vpetersson Maybe it would be worthwhile to make it so that the title of the page or the title of the post would be added to the main title via a dash?

**Comment by etf-yrm** [comment]
I have in view of something like this: {% assign title = site.title | append: ' - ' | append: page.title  %}

**Comment by vpetersson** [comment]
> Maybe it would be worthwhile to make it so that the title of the page or the title of the post would be added to the main title via a dash?

Right so I don't really care what order we do them in, but I want to include both the [page title](https://github.com/WoTTsecurity/wott-io/blob/master/_config.yml#L12) and blog post title


Note, on the front page, it should be:

[site title](https://github.com/WoTTsecurity/wott-io/blob/master/_config.yml#L12) - [site description](https://github.com/WoTTsecurity/wott-io/blob/master/_config.yml#L13)

On regular content pages, it should be site title and page title.

Does that make sense?

**Comment by etf-yrm** [comment]
@vpetersson ok, implement as you describe
