### ISSUE TITLE
Fix formatting of blog posts

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/wott-io#98]
The blog post listings are misaligned below.
![Screenshot_2019-07-15 Blog](https://user-images.githubusercontent.com/357664/61206467-8c6ca800-a6ea-11e9-95ab-01a7bf2e90df.jpg)

**Comment by etf-yrm** [comment]
@vpetersson    in order to solve this problem, I need to know in which browser and which version (if known) the list of posts is displayed incorrectly

**Comment by vpetersson** [comment]
Firefox (latest version I assume) on Linux.

**Comment by etf-yrm** [comment]
![Снимок экрана от 2019-07-18 19-24-28](https://user-images.githubusercontent.com/51322344/61461078-d3c89200-a991-11e9-84dd-64aa0a3ee832.png)
I checked Firefox on Linux (Ubuntu) in the latest browser version, the display is correct

**Comment by vpetersson** [comment]
Make the window more narrow. The issue happens when you can only fit two in width.

**Comment by etf-yrm** [comment]
@vpetersson but when the screen is narrowed down, the blocks will be scaled depending on the width, including all the content in these blocks. I will try different variations in width, but so far I have not been able to observe this.
