### ISSUE TITLE
Fix in-line code blocks

### ISSUE THREAD

**Issue by vpetersson** [WoTTsecurity/wott-io#99]
Inline code blocks (i.e. `foobar`) are not being formatted properly. They should be formatted like they are here on Github.

**Comment by etf-yrm** [comment]
@vpetersson what exactly is the problem? I just see that for example visually https://github.com/WoTTsecurity/wott-io/blob/master/_posts/2019-07-18-edge-to-kubernetes.md and https://wott.io/blog / tutorials / 2019/07/18 / edge-to-kubernetes, the code blocks look identical except for the background and text colors.
We use the standard syntax highlighting method: 
markdown: kramdown
highlighter: rouge

**Comment by vpetersson** [comment]
Look at this this screenshot:
<img width="790" alt="Screen Shot 2019-07-19 at 11 48 16 AM" src="https://user-images.githubusercontent.com/357664/61530150-2dc16a00-aa1b-11e9-8675-cb1187ab43de.png">

Now compare that to how it looks at Github:
<img width="651" alt="Screen Shot 2019-07-19 at 11 49 57 AM" src="https://user-images.githubusercontent.com/357664/61530211-5d707200-aa1b-11e9-9da8-f9911cdb99ed.png">

The way that Github does it is the proper way to do it.

You're right, it might only be a matter of background and colors, but that makes a huge difference for readability.
